name: Ruby

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby_version: [2.6, 2.7]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
      - name: Install apt dependencies
        run: sudo apt-get install -y libsox-fmt-all sox libchromaprint-dev espeak lame
      - name: Install gem dependencies
        run: bundle install
      - name: Rubocop Linter Action
        uses: andrewmcodes/rubocop-linter-action@v3.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true  
      - name: Run tests
        run: bundle exec rspec
